import fs from "node:fs/promises"
import path from "node:path"
import {fileURLToPath} from "node:url"
import {createRequire} from "node:module"

const __dirname = path.dirname(
	fileURLToPath(import.meta.url)
)

const require = createRequire(import.meta.url)

const master_slave_package = (await fs.readFile(
	require.resolve("@anio-js-foundation/master-slave-protocol")
)).toString()

let index = (await fs.readFile(
	path.resolve(__dirname, "src", "index.template.mjs")
)).toString()

index = index.split(`$master-slave-protocol-base64$`).join(
	Buffer.from(master_slave_package).toString("base64")
)

const warning = `/**
 * DO NOT EDIT THIS FILE DIRECTLY, IT IS AUTOMATICALLY GENERATED BY A SCRIPT.
 */
`

await fs.writeFile(
	path.resolve(__dirname, "src", "index.mjs"), warning + index
)
